baseURL = "https://stwi.blog/"
canonifyURLs = "true"
staticDir = "static"
publishDir = "docs"
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "hugo-theme-learn"
disqusShortname = "save-the-world"
hasCJKLanguage = false
metaDataFormat = "yaml"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[markup.goldmark.renderer]
    unsafe= true

[params]
    disableLandingPageButton = true
    disableMermaid = true
    custom_css = ["css/spiral.css", "css/custom.css"]

    # Source Code repository section
    description = "A plan to save the world"
    github_repository = "https://github.com/cosmosgame/save-the-world"
    version = "0.2.0"
    editURL = "https://github.com/cosmosgame/save-the-world/tree/master/content/"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/cosmosgame/save-the-world"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    title = "Save The World"
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = "#a796d6"

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry"
  ]

[outputs]
    home = ["HTML", "RSS", "JSON"]
